
title: SimpleFIN
email: matt@simplefin.org
description: SimpleFIN is a protocol for simple financial aggregation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simplefin.org"

# Build settings
markdown: kramdown
highlighter: pygments